name: Sentra Repository Risk Score
description: The first autonomous source code posture risk score tool
author: LESIS
branding:
  icon: "shield"
  color: "blue"

inputs:
  dependency:
    description: 'Check if repositories have dependabot.yml file'
    required: false
    default: 'true'
  maintained:
    description: 'Get alerts about repositories with a last commit date greater than 90 days old'
    required: false
    default: 'true'
  metrics:
    description: 'Extract some metrics based on GHAS'
    required: false
    default: 'true'
  token:
    description: 'Token to access the GitHub API'
    required: true
  org:
    description: 'GitHub organization to interact with'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run sentra
      run: |
        docker run ghcr.io/instriq/sentra/sentra:latest \
          --org ${{ inputs.org }} \
          --token ${{ inputs.token }} \
          ${{ inputs.dependency != 'true' && '--dependency' || '' }} \
          ${{ inputs.maintained != 'true' && '--maintained' || '' }} \
          ${{ inputs.metrics != 'true' && '--metrics' || '' }}
